### ISSUE TITLE
Crashes if FLATPAK_MALIIT_CONTAINER_DBUS is not set

### ISSUE THREAD

**Issue by ArturGaspar** [sailfishos-chum/qt-sfos-maliit-platforminputcontext#1]
```
#0  0x0000007fefb1d660 in QDBusAbstractInterface::isValid() const () from /opt/qt5/lib64/qt5/plugins/platforms/../../../libQt5DBus.so.5
#1  0x0000007fef4d319c in MInputContext::updateInputMethodArea (this=0x484560, rect=...) at /usr/src/debug/opt-qt5-sfos-maliit-platforminputcontext-1.0.1-1.1.1.jolla.aarch64/input-context/minputcontext.cpp:645
```

The crash is at https://github.com/sailfishos-flatpak/maliit-framework/blob/c1ce5ed850597cf7b0a1ea22cd6450bf4217092e/input-context/minputcontext.cpp#L645:
```
        if (containerConnectionInterface && containerConnectionInterface->isValid()) {
```

Earlier, if the environment variable is empty, `containerConnectionInterface` never gets initialised, https://github.com/sailfishos-flatpak/maliit-framework/blob/c1ce5ed850597cf7b0a1ea22cd6450bf4217092e/input-context/minputcontext.cpp#L94:
```
    QString flAddress = QString::fromLatin1(qgetenv("FLATPAK_MALIIT_CONTAINER_DBUS"));
    if (!flAddress.isEmpty()) {
```

**Comment by ArturGaspar** [comment]
Workaround: `FLATPAK_MALIIT_CONTAINER_DBUS=$DBUS_SESSION_BUS_ADDRESS`
